import { useEffect, useState } from 'react';
import { Flag, Package, Scale, Users, Wrench } from 'lucide-react';
import { Link } from 'react-router-dom';
import api from '../../api';

export default function AdminDashboard() {
  const [stats, setStats] = useState(null);
  useEffect(() => { api.get('/admin/stats').then((response) => setStats(response.data)); }, []);
  const cards = stats ? [{ label: 'Users', value: stats.users, icon: Users, link: '/admin/users', tone: 'bg-cobalt text-white' }, { label: 'Listings', value: stats.listings, icon: Package, link: '/admin/listings', tone: 'bg-lime text-ink' }, { label: 'Services', value: stats.services, icon: Wrench, link: '/admin/listings', tone: 'bg-mango text-ink' }, { label: 'Reports', value: stats.pendingReports, icon: Flag, link: '/admin/reports', tone: 'bg-coral text-white' }] : [];
  return <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 md:px-8 md:py-12"><h1 className="display-type text-5xl leading-none">Admin</h1><p className="mt-3 text-sm text-muted">Moderation, finance, and operational controls.</p>{!stats ? <div className="mt-8 grid grid-cols-2 gap-3 md:grid-cols-4">{Array.from({ length: 4 }).map((_, index) => <div key={index} className="h-32 animate-pulse rounded-[14px] bg-ink/10" />)}</div> : <div className="mt-8 grid grid-cols-2 gap-3 md:grid-cols-4">{cards.map(({ label, value, icon: Icon, link, tone }) => <Link key={label} to={link} className={`rounded-[14px] p-5 shadow-card transition hover:-translate-y-0.5 ${tone}`}><Icon className="h-6 w-6" /><strong className="mt-7 block text-3xl">{value}</strong><span className="mt-1 block text-sm font-bold opacity-70">{label}</span></Link>)}</div>}<div className="mt-8 grid gap-3 md:grid-cols-2"><Link to="/admin/finance" className="notice-slip group flex min-h-32 items-center gap-4 p-5 transition hover:shadow-card-hover"><span className="flex h-12 w-12 items-center justify-center rounded-[12px] bg-ink text-paper"><Scale className="h-5 w-5" /></span><span><strong className="block">Finance controls</strong><span className="mt-1 block text-sm text-muted">Review disputes, withdrawals, refunds, and audit records.</span></span></Link><Link to="/admin/reports" className="notice-slip group flex min-h-32 items-center gap-4 p-5 transition hover:shadow-card-hover"><span className="flex h-12 w-12 items-center justify-center rounded-[12px] bg-coral text-white"><Flag className="h-5 w-5" /></span><span><strong className="block">Content reports</strong><span className="mt-1 block text-sm text-muted">Review reports and moderation decisions.</span></span></Link></div></div>;
}
